version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "04:00" # UTC
    labels:
      - "domain: deps"
      - "no-changelog"
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 10
    groups:
      all-cargo:
        patterns:
          - "*"
  - package-ecosystem: "docker"
    directory: "/distribution/docker/debian"
    schedule:
      interval: "monthly"
      time: "04:00" # UTC
    labels:
      - "domain: releasing"
      - "no-changelog"
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 5
    groups:
      all-docker:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "domain: ci"
      - "no-changelog"
    commit-message:
      prefix: "chore(ci)"
    open-pull-requests-limit: 5
    groups:
      all-actions:
        patterns:
          - "*"
