# https://github.com/grafana/loki/blob/main/cmd/loki/loki-local-config.yaml
auth_enabled: false

server:
  http_listen_port: 3100

common:
  instance_addr: 0.0.0.0
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

limits_config:
  otlp_config:
    resource_attributes:
      ignore_defaults: true
      attributes_config:
        - action: index_label
          attributes:
            - service.name
            - service.namespace
            - service.version
            - deployment.environment
        - action: drop
          regex: "^$"
    scope_attributes:
      - action: drop
        regex: "^$"
    log_attributes:
      - action: drop
        regex: "^$"

ruler:
  alertmanager_url: http://localhost:9093

analytics:
  reporting_enabled: false
