{
 "title": "Node Exporter (Sol host_metrics)",
 "description": "Host metrics dashboard for Sol (Vector fork) using the host_metrics source. Adapted from Node Exporter Full (Grafana ID 1860, rev 45).",
 "tags": [ "linux" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "service_name",
    "query": {
     "query": "label_values(node_uptime, service_name)"
    }
   },
   {
    "name": "host",
    "query": {
     "query": "label_values(node_uptime{service_name=\"${service_name}\"}, host)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   }
  ]
 },
 "panels": [
  { "title": "Quick CPU / Mem / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Overall CPU busy percentage (averaged across all cores)",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\",host=\"$host\",service_name=\"${service_name}\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Sys Load",
   "type": "gauge",
   "description": "System load over all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(node_load1{host=\"$host\",service_name=\"${service_name}\"}) * 100 / count(count(node_cpu_seconds_total{host=\"$host\",service_name=\"${service_name}\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Real RAM usage excluding cache and reclaimable memory",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min((1 - (node_memory_available_bytes{host=\"$host\", service_name=\"${service_name}\"} / node_memory_total_bytes{host=\"$host\", service_name=\"${service_name}\"})) * 100, 0)"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Percentage of swap space currently used by the system",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_swap_total_bytes{host=\"$host\",service_name=\"${service_name}\"} > bool 0) * ((node_memory_swap_total_bytes{host=\"$host\",service_name=\"${service_name}\"} - node_memory_swap_free_bytes{host=\"$host\",service_name=\"${service_name}\"}) / (node_memory_swap_total_bytes{host=\"$host\",service_name=\"${service_name}\"})) * 100"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (node_filesystem_total_bytes{host=\"$host\", service_name=\"${service_name}\", mountpoint=\"/\", filesystem!=\"rootfs\"}\n   - node_filesystem_free_bytes{host=\"$host\", service_name=\"${service_name}\", mountpoint=\"/\", filesystem!=\"rootfs\"})\n  / node_filesystem_total_bytes{host=\"$host\", service_name=\"${service_name}\", mountpoint=\"/\", filesystem!=\"rootfs\"}\n) * 100\n"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{host=\"$host\",service_name=\"${service_name}\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_total_bytes{host=\"$host\",service_name=\"${service_name}\"}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_swap_total_bytes{host=\"$host\",service_name=\"${service_name}\"}"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_total_bytes{host=\"$host\",service_name=\"${service_name}\",mountpoint=\"/\",filesystem!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uptime{host=\"$host\",service_name=\"${service_name}\"}"
    }
   ]
  },
  { "title": "Basic CPU / Mem / Net / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "CPU time spent busy vs idle, split by activity type",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{host=\"$host\",service_name=\"${service_name}\", mode=\"system\"}[$__rate_interval]))",
     "legendFormat": "Busy System"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{host=\"$host\",service_name=\"${service_name}\", mode=\"user\"}[$__rate_interval]))",
     "legendFormat": "Busy User"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{host=\"$host\",service_name=\"${service_name}\", mode=\"iowait\"}[$__rate_interval]))",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "avg(sum without(mode) (rate(node_cpu_seconds_total{host=\"$host\",service_name=\"${service_name}\", mode=~\".*irq\"}[$__rate_interval])))",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "avg(sum without (mode) (rate(node_cpu_seconds_total{host=\"$host\",service_name=\"${service_name}\",  mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[$__rate_interval])))",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{host=\"$host\",service_name=\"${service_name}\", mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "RAM and swap usage overview, including caches",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_total_bytes{host=\"$host\",service_name=\"${service_name}\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_free_bytes{host=\"$host\",service_name=\"${service_name}\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "(node_memory_swap_total_bytes{host=\"$host\",service_name=\"${service_name}\"} - node_memory_swap_free_bytes{host=\"$host\",service_name=\"${service_name}\"})",
     "legendFormat": "Swap used"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Per-interface network traffic (receive and transmit) in bits per second",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{host=\"$host\",service_name=\"${service_name}\"}[$__rate_interval])*8",
     "legendFormat": "Rx {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{host=\"$host\",service_name=\"${service_name}\"}[$__rate_interval])*8",
     "legendFormat": "Tx {{device}}"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "timeseries",
   "description": "Percentage of filesystem space used for each mounted device",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((node_filesystem_total_bytes{host=\"$host\", service_name=\"${service_name}\", device!~'rootfs'} - node_filesystem_free_bytes{host=\"$host\", service_name=\"${service_name}\", device!~'rootfs'}) / node_filesystem_total_bytes{host=\"$host\", service_name=\"${service_name}\", device!~'rootfs'}) * 100",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "CPU / Memory / Net / Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "description": "CPU time usage split by state, normalized across all CPU cores",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(node_cpu_seconds_total{mode=\"system\",host=\"$host\",service_name=\"${service_name}\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{host=\"$host\",service_name=\"${service_name}\"}) by (cpu)))",
       "legendFormat": "System - Processes executing in kernel mode"
      },
      {
       "expr": "sum(rate(node_cpu_seconds_total{mode=\"user\",host=\"$host\",service_name=\"${service_name}\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{host=\"$host\",service_name=\"${service_name}\"}) by (cpu)))",
       "legendFormat": "User - Normal processes executing in user mode"
      },
      {
       "expr": "sum(rate(node_cpu_seconds_total{mode=\"nice\",host=\"$host\",service_name=\"${service_name}\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{host=\"$host\",service_name=\"${service_name}\"}) by (cpu)))",
       "legendFormat": "Nice - Niced processes executing in user mode"
      },
      {
       "expr": "sum(rate(node_cpu_seconds_total{mode=\"iowait\",host=\"$host\",service_name=\"${service_name}\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{host=\"$host\",service_name=\"${service_name}\"}) by (cpu)))",
       "legendFormat": "Iowait - Waiting for I/O to complete"
      },
      {
       "expr": "sum(rate(node_cpu_seconds_total{mode=\"irq\",host=\"$host\",service_name=\"${service_name}\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{host=\"$host\",service_name=\"${service_name}\"}) by (cpu)))",
       "legendFormat": "Irq - Servicing interrupts"
      },
      {
       "expr": "sum(rate(node_cpu_seconds_total{mode=\"softirq\",host=\"$host\",service_name=\"${service_name}\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{host=\"$host\",service_name=\"${service_name}\"}) by (cpu)))",
       "legendFormat": "Softirq - Servicing softirqs"
      },
      {
       "expr": "sum(rate(node_cpu_seconds_total{mode=\"steal\",host=\"$host\",service_name=\"${service_name}\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{host=\"$host\",service_name=\"${service_name}\"}) by (cpu)))",
       "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
      },
      {
       "expr": "sum(rate(node_cpu_seconds_total{mode=\"idle\",host=\"$host\",service_name=\"${service_name}\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{host=\"$host\",service_name=\"${service_name}\"}) by (cpu)))",
       "legendFormat": "Idle - Waiting for something to happen"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "description": "Breakdown of physical memory and swap usage. Hardware-detected memory errors are also displayed",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_cached_bytes{host=\"$host\",service_name=\"${service_name}\"}",
       "legendFormat": "Cache - Parked file data (file content) cache"
      },
      {
       "expr": "node_memory_buffers_bytes{host=\"$host\",service_name=\"${service_name}\"}",
       "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
      },
      {
       "expr": "node_memory_free_bytes{host=\"$host\",service_name=\"${service_name}\"}",
       "legendFormat": "Unused - Free memory unassigned"
      },
      {
       "expr": "(node_memory_swap_total_bytes{host=\"$host\",service_name=\"${service_name}\"} - node_memory_swap_free_bytes{host=\"$host\",service_name=\"${service_name}\"})",
       "legendFormat": "Swap - Swap space used"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "timeseries",
     "description": "Incoming and outgoing network traffic per interface",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 433 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{host=\"$host\",service_name=\"${service_name}\"}[$__rate_interval])*8",
       "legendFormat": "{{device}} - Rx in"
      },
      {
       "expr": "rate(node_network_transmit_bytes_total{host=\"$host\",service_name=\"${service_name}\"}[$__rate_interval])*8",
       "legendFormat": "{{device}} - Tx out"
      }
     ]
    },
    {
     "title": "Disk IOps",
     "type": "timeseries",
     "description": "Disk I/O operations per second for each device",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 445 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(node_disk_reads_completed_total{host=\"$host\",service_name=\"${service_name}\",device=~\"[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Read"
      },
      {
       "expr": "rate(node_disk_writes_completed_total{host=\"$host\",service_name=\"${service_name}\",device=~\"[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Write"
      }
     ]
    },
    {
     "title": "Disk Throughput",
     "type": "timeseries",
     "description": "Disk I/O throughput per device",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 445 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total{host=\"$host\",service_name=\"${service_name}\",device=~\"[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Read"
      },
      {
       "expr": "rate(node_disk_written_bytes_total{host=\"$host\",service_name=\"${service_name}\",device=~\"[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Write"
      }
     ]
    },
    {
     "title": "Filesystem Space Available",
     "type": "timeseries",
     "description": "Amount of available disk space per mounted filesystem, excluding rootfs. Based on block availability to non-root users",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 457 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_filesystem_free_bytes{host=\"$host\",service_name=\"${service_name}\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Filesystem Used",
     "type": "timeseries",
     "description": "Disk usage (used = total - available) per mountpoint",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 457 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_filesystem_total_bytes{host=\"$host\",service_name=\"${service_name}\",device!~'rootfs'} - node_filesystem_free_bytes{host=\"$host\",service_name=\"${service_name}\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Read/Write IOps",
     "type": "timeseries",
     "description": "Number of I/O operations completed per second for the device (after merges), including both reads and writes",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(node_disk_reads_completed_total{host=\"$host\",service_name=\"${service_name}\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Read"
      },
      {
       "expr": "rate(node_disk_writes_completed_total{host=\"$host\",service_name=\"${service_name}\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Write"
      }
     ]
    },
    {
     "title": "Disk Read/Write Data",
     "type": "timeseries",
     "description": "Number of bytes read from or written to the device per second",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total{host=\"$host\",service_name=\"${service_name}\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Read"
      },
      {
       "expr": "rate(node_disk_written_bytes_total{host=\"$host\",service_name=\"${service_name}\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Write"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Filesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "File Nodes Free",
     "type": "timeseries",
     "description": "Number of free file nodes (inodes) available per mounted filesystem. A low count may prevent file creation even if disk space is available",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_filesystem_inodes_free{host=\"$host\",service_name=\"${service_name}\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "File Nodes Size",
     "type": "timeseries",
     "description": "Number of file nodes (inodes) available per mounted filesystem. Reflects maximum file capacity regardless of disk size",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 370 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_filesystem_inodes_total{host=\"$host\",service_name=\"${service_name}\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic by Packets",
     "type": "timeseries",
     "description": "Number of network packets received and transmitted per second, by interface.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_packets_total{host=\"$host\",service_name=\"${service_name}\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Rx in"
      },
      {
       "expr": "rate(node_network_transmit_packets_total{host=\"$host\",service_name=\"${service_name}\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Tx out"
      }
     ]
    },
    {
     "title": "Network Traffic Errors",
     "type": "timeseries",
     "description": "Rate of packet-level errors for each network interface. Receive errors may indicate physical or driver issues; transmit errors may reflect collisions or hardware faults",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_errs_total{host=\"$host\",service_name=\"${service_name}\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Rx in"
      },
      {
       "expr": "rate(node_network_transmit_errs_total{host=\"$host\",service_name=\"${service_name}\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Tx out"
      }
     ]
    }
   ]
  }
 ]
}