name: Build & Publish

on:
  push:
    branches: [main]
    tags: ["v*"]

permissions:
  contents: write
  packages: write

env:
  VERBOSE: true
  CI: true
  CARGO_PROFILE_RELEASE_LTO: fat
  CARGO_PROFILE_RELEASE_CODEGEN_UNITS: 1

jobs:
  checks:
    name: Checks
    uses: ./.github/workflows/checks.yml
    with:
      component-validation: true

  generate-metadata:
    name: Generate version metadata
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    outputs:
      sol_version: ${{ steps.meta.outputs.sol_version }}
      sol_build_desc: ${{ steps.meta.outputs.sol_build_desc }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/setup
        with:
          rust: true
      - name: Generate publish metadata
        id: meta
        run: make ci-generate-publish-metadata

  build-windows:
    name: Build Windows x86_64 zip
    runs-on: windows-2025
    timeout-minutes: 90
    needs:
      - checks
      - generate-metadata
    env:
      SOL_VERSION: ${{ needs.generate-metadata.outputs.sol_version }}
      SOL_BUILD_DESC: ${{ needs.generate-metadata.outputs.sol_build_desc }}
      RELEASE_BUILDER: "true"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Bootstrap runner environment
        run: .\scripts\environment\bootstrap-windows-2025.ps1
      - name: Build archive
        shell: bash
        run: FEATURES=default-msvc ARCHIVE_TYPE=zip NATIVE_BUILD=true TARGET=x86_64-pc-windows-msvc make package
      - name: Upload artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: sol-${{ env.SOL_VERSION }}-x86_64-pc-windows-msvc
          path: target/artifacts/sol*

  docker:
    name: Docker images
    needs:
      - checks
      - generate-metadata
    uses: ./.github/workflows/docker-build.yml
    with:
      sol-version: ${{ needs.generate-metadata.outputs.sol_version }}
      sol-build-desc: ${{ needs.generate-metadata.outputs.sol_build_desc }}
    secrets: inherit
