name: CI

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'demo/**'
      - '**.md'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  VERBOSE: true
  CI: true

permissions:
  contents: read

jobs:
  checks:
    name: Checks
    uses: ./.github/workflows/checks.yml
    with:
      component-validation: true

  test-windows:
    name: Unit tests (Windows)
    runs-on: windows-2025
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.10"
      - run: .\scripts\environment\bootstrap-windows-2025.ps1
      - run: make test

  check-deny:
    name: Security & license audit
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    env:
      CARGO_INCREMENTAL: 0
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/setup
        with:
          mold: false
          cargo-deny: true
      - run: make check-deny

  generate-metadata:
    name: Generate version metadata
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    outputs:
      sol_version: ${{ steps.meta.outputs.sol_version }}
      sol_build_desc: ${{ steps.meta.outputs.sol_build_desc }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/setup
        with:
          rust: true
      - name: Generate publish metadata
        id: meta
        run: make ci-generate-publish-metadata

  docker:
    name: Docker images
    needs:
      - checks
      - generate-metadata
    uses: ./.github/workflows/docker-build.yml
    with:
      sol-version: ${{ needs.generate-metadata.outputs.sol_version }}
      sol-build-desc: ${{ needs.generate-metadata.outputs.sol_build_desc }}
    secrets: inherit

  all-checks:
    name: CI
    runs-on: ubuntu-24.04
    if: always()
    needs:
      - checks
      - test-windows
      - check-deny
      - docker
    steps:
      - name: Check all jobs status
        run: |
          if [[ "${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            echo "One or more jobs failed or were cancelled"
            exit 1
          else
            echo "All jobs completed successfully"
          fi
